### ISSUE TITLE
Remote server disconnected but able to get character details

### ISSUE THREAD

**Issue by josseepphh15** [AlSch092/Mir4-PacketEncryption#3]
![image](https://github.com/user-attachments/assets/6d59010a-f0fe-4114-9f43-7a9ad8880ccd)

Hello, what is the possible issue for this?

**Comment by AlSch092** [comment]
Wrong encryption key, needs to be updated by someone (not me, have no free time anymore)

**Comment by josseepphh15** [comment]
Thanks, Can you give me an idea how did you get TextCipherKey, EncryptionKey, EncryptPacketFunction so I can do a bit of research?

**Comment by AlSch092** [comment]
Reverse engineering the game client, all of the information needed to update it is there in the project.
